export type EmojiCategory =
  | 'PESSOAS'
  | 'NATUREZA'
  | 'ALIMENTOS'
  | 'ATIVIDADES'
  | 'VIAGEM'
  | 'OBJETOS'
  | 'SIMBOLOS'
  | 'BANDEIRAS';

const emojis: Record<EmojiCategory, { name: string; label: string }[]> = {
  PESSOAS: [
    { name: "😀", label: "Grinning Face" },
    { name: "😁", label: "Beaming Face with Smiling Eyes" },
    { name: "😂", label: "Face with Tears of Joy" },
    { name: "🤣", label: "Rolling on the Floor Laughing" },
    { name: "😃", label: "Grinning Face with Big Eyes" },
    { name: "😄", label: "Grinning Face with Smiling Eyes" },
    { name: "😅", label: "Grinning Face with Sweat" },
    { name: "😆", label: "Grinning Squinting Face" },
    { name: "😉", label: "Winking Face" },
    { name: "😊", label: "Smiling Face with Smiling Eyes" },
    { name: "😇", label: "Smiling Face with Halo" },
    { name: "😍", label: "Heart Eyes" },
    { name: "😜", label: "Face with Stuck-Out Tongue and Winking Eye" },
    { name: "😎", label: "Smiling Face with Sunglasses" },
    { name: "😏", label: "Smirking Face" },
    { name: "😒", label: "Unamused Face" },
    { name: "😞", label: "Disappointed Face" },
    { name: "😔", label: "Pensive Face" },
    { name: "😟", label: "Worried Face" },
    { name: "😢", label: "Crying Face" },
    { name: "😭", label: "Loudly Crying Face" },
    { name: "😱", label: "Face Screaming in Fear" },
    { name: "😳", label: "Flushed Face" },
    { name: "🤯", label: "Exploding Head" },
    { name: "🥺", label: "Pleading Face" },
    { name: "😤", label: "Face with Steam From Nose" },
    { name: "😡", label: "Pouting Face" },
    { name: "😠", label: "Angry Face" },
    { name: "🤬", label: "Face with Symbols on Mouth" },
    { name: "🤧", label: "Sneezing Face" },
  ],
  NATUREZA: [
    { name: "🌳", label: "Tree" },
    { name: "🌵", label: "Cactus" },
    { name: "🌊", label: "Water Wave" },
    { name: "🌱", label: "Seedling" },
    { name: "🍀", label: "Four Leaf Clover" },
    { name: "🌼", label: "Blossom" },
    { name: "🌸", label: "Cherry Blossom" },
    { name: "🌺", label: "Hibiscus" },
    { name: "🌻", label: "Sunflower" },
    { name: "🌷", label: "Tulip" },
    { name: "🌾", label: "Sheaf of Rice" },
    { name: "🍁", label: "Maple Leaf" },
    { name: "🍂", label: "Fallen Leaf" },
    { name: "🍃", label: "Leaf Fluttering in Wind" },
    { name: "🌍", label: "Earth Globe Europe-Africa" },
    { name: "🌎", label: "Earth Globe Americas" },
    { name: "🌏", label: "Earth Globe Asia-Australia" },
    { name: "🌑", label: "New Moon" },
    { name: "🌒", label: "Waxing Crescent Moon" },
    { name: "🌓", label: "First Quarter Moon" },
    { name: "🌔", label: "Waxing Gibbous Moon" },
    { name: "🌕", label: "Full Moon" },
    { name: "🌖", label: "Waning Gibbous Moon" },
    { name: "🌗", label: "Last Quarter Moon" },
    { name: "🌘", label: "Waning Crescent Moon" },
    { name: "🌙", label: "Crescent Moon" },
    { name: "🌚", label: "New Moon with Face" },
    { name: "🌛", label: "Waning Crescent Moon with Face" },
  ],
  ALIMENTOS: [
    { name: "🍎", label: "Red Apple" },
    { name: "🍏", label: "Green Apple" },
    { name: "🍊", label: "Tangerine" },
    { name: "🍌", label: "Banana" },
    { name: "🍒", label: "Cherries" },
    { name: "🍓", label: "Strawberry" },
    { name: "🥝", label: "Kiwi Fruit" },
    { name: "🍍", label: "Pineapple" },
    { name: "🍑", label: "Peach" },
    { name: "🍈", label: "Melon" },
    { name: "🍋", label: "Lemon" },
    { name: "🍇", label: "Grapes" },
    { name: "🍉", label: "Watermelon" },
    { name: "🍅", label: "Tomato" },
    { name: "🥥", label: "Coconut" },
    { name: "🥑", label: "Avocado" },
    { name: "🥔", label: "Potato" },
    { name: "🥕", label: "Carrot" },
    { name: "🌽", label: "Ear of Corn" },
    { name: "🌶️", label: "Hot Pepper" },
    { name: "🥒", label: "Cucumber" },
    { name: "🥦", label: "Broccoli" },
    { name: "🍄", label: "Mushroom" },
    { name: "🥩", label: "Cut of Meat" },
    { name: "🍗", label: "Poultry Leg" },
    { name: "🍖", label: "Meat on Bone" },
    { name: "🍕", label: "Pizza" },
    { name: "🍔", label: "Hamburger" },
    { name: "🌭", label: "Hot Dog" },
    { name: "🥪", label: "Sandwich" },
    { name: "🥗", label: "Green Salad" },
    { name: "🍲", label: "Pot of Food" },
    { name: "🍿", label: "Popcorn" },
    { name: "🥣", label: "Bowl with Spoon" },
    { name: "🍩", label: "Doughnut" },
    { name: "🍪", label: "Cookie" },
    { name: "🎂", label: "Birthday Cake" },
    { name: "🍰", label: "Shortcake" },
    { name: "🧁", label: "Cupcake" },
    { name: "🍦", label: "Ice Cream" },
    { name: "🍧", label: "Shaved Ice" },
    { name: "🍨", label: "Ice Cream" },
  ],
  ATIVIDADES: [
    { name: "⚽", label: "Soccer Ball" },
    { name: "🏀", label: "Basketball" },
    { name: "🏈", label: "American Football" },
    { name: "⚾", label: "Baseball" },
    { name: "🎾", label: "Tennis Ball" },
    { name: "🏐", label: "Volleyball" },
    { name: "🏉", label: "Rugby Football" },
    { name: "🎱", label: "Billiards" },
    { name: "🥏", label: "Flying Disc" },
    { name: "🎳", label: "Bowling" },
    { name: "🥇", label: "1st Place Medal" },
    { name: "🥈", label: "2nd Place Medal" },
    { name: "🥉", label: "3rd Place Medal" },
    { name: "🏆", label: "Trophy" },
    { name: "🏅", label: "Sports Medal" },
    { name: "🎖️", label: "Military Medal" },
    { name: "🥋", label: "Martial Arts Uniform" },
    { name: "🎮", label: "Video Game" },
    { name: "🎲", label: "Game Die" },
    { name: "🧩", label: "Puzzle Piece" },
  ],
  VIAGEM: [
    { name: "✈️", label: "Airplane" },
    { name: "🛳️", label: "Ship" },
    { name: "🚂", label: "Train" },
    { name: "🚋", label: "Tram" },
    { name: "🚃", label: "Locomotive" },
    { name: "🚄", label: "High-Speed Train" },
    { name: "🚅", label: "Bullet Train" },
    { name: "🚗", label: "Car" },
    { name: "🚕", label: "Taxi" },
    { name: "🚙", label: "Sport Utility Vehicle" },
    { name: "🚚", label: "Delivery Truck" },
    { name: "🚛", label: "Articulated Lorry" },
    { name: "🚜", label: "Tractor" },
    { name: "🚲", label: "Bicycle" },
    { name: "🛴", label: "Kick Scooter" },
    { name: "🛵", label: "Motor Scooter" },
    { name: "🚠", label: "Mountain Cableway" },
    { name: "🚡", label: "Aerial Tramway" },
    { name: "🛳️", label: "Ship" },
  ],
  OBJETOS: [
    { name: "📱", label: "Mobile Phone" },
    { name: "💻", label: "Laptop" },
    { name: "🖥️", label: "Desktop Computer" },
    { name: "🖨️", label: "Printer" },
    { name: "⌨️", label: "Keyboard" },
    { name: "🖱️", label: "Computer Mouse" },
    { name: "🖲️", label: "Trackball" },
    { name: "💾", label: "Floppy Disk" },
    { name: "📷", label: "Camera" },
    { name: "📸", label: "Camera with Flash" },
    { name: "📹", label: "Video Camera" },
    { name: "📼", label: "VHS Tape" },
    { name: "📞", label: "Telephone" },
    { name: "📟", label: "Pager" },
    { name: "📠", label: "Fax Machine" },
    { name: "📺", label: "Television" },
    { name: "📻", label: "Radio" },
    { name: "🎙️", label: "Studio Microphone" },
    { name: "🎚️", label: "Level Slider" },
    { name: "🎛️", label: "Control Knobs" },
    { name: "🧭", label: "Compass" },
    { name: "⏰", label: "Alarm Clock" },
    { name: "🕰️", label: "Mantelpiece Clock" },
    { name: "⌛", label: "Hourglass Done" },
    { name: "⏳", label: "Hourglass Not Done" },
  ],
  SIMBOLOS: [
    { name: "❤️", label: "Heart" },
    { name: "💛", label: "Yellow Heart" },
    { name: "💚", label: "Green Heart" },
    { name: "💙", label: "Blue Heart" },
    { name: "💜", label: "Purple Heart" },
    { name: "🖤", label: "Black Heart" },
    { name: "🤍", label: "White Heart" },
    { name: "🤎", label: "Brown Heart" },
    { name: "💔", label: "Broken Heart" },
    { name: "❤️‍🔥", label: "Heart on Fire" },
    { name: "⭐", label: "Star" },
    { name: "🌟", label: "Glowing Star" },
    { name: "✨", label: "Sparkles" },
    { name: "⚡", label: "High Voltage" },
    { name: "🔥", label: "Fire" },
    { name: "💧", label: "Droplet" },
    { name: "🌈", label: "Rainbow" },
    { name: "🌞", label: "Sun with Face" },
    { name: "🌝", label: "Full Moon with Face" },
    { name: "🌓", label: "First Quarter Moon" },
    { name: "🌙", label: "Crescent Moon" },
  ],
  BANDEIRAS: [
    { name: "🇧🇷", label: "Brazil" },
    { name: "🇺🇸", label: "United States" },
    { name: "🇨🇦", label: "Canada" },
    { name: "🇬🇧", label: "United Kingdom" },
    { name: "🇮🇳", label: "India" },
    { name: "🇫🇷", label: "France" },
    { name: "🇩🇪", label: "Germany" },
    { name: "🇯🇵", label: "Japan" },
    { name: "🇨🇳", label: "China" },
    { name: "🇮🇹", label: "Italy" },
    { name: "🇲🇽", label: "Mexico" },
    { name: "🇪🇸", label: "Spain" },
    { name: "🇮🇱", label: "Israel" },
    { name: "🇦🇺", label: "Australia" },
    { name: "🇷🇺", label: "Russia" },
    { name: "🇷🇴", label: "Romania" },
    { name: "🇧🇪", label: "Belgium" },
    { name: "🇮🇪", label: "Ireland" },
    { name: "🇺🇾", label: "Uruguay" },
  ]
};

export default emojis;
